version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    restart: on-failure
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=MyP4ssw0rd!!
    networks:
      - app
    healthcheck:
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
      test: ["CMD", "mongosh", "--quiet", "127.0.0.1/admin", "--eval", "'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)'"]

  auth-api:
    build:
      context: ./auth-service
    ports:
      - "8081:8080"
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - app
      
  joueur-api:
    build:
      context: ./joueur-service
    ports:
      - "8082:8080"
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - app
      
  monstre-api:
    build:
      context: ./monstre-service
    ports:
      - "8083:8080"
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - app

networks:
  app:
