version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    restart: on-failure
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=MyP4ssw0rd!!
      - MONGO_INITDB_DATABASE=gatcha_api
    volumes:
       - mongo-data:/data/db
    networks:
      - backend
    healthcheck:
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
      test:
        [
          "CMD",
          "mongosh",
          "--quiet",
          "127.0.0.1/gatcha_api",
          "--eval",
          "'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)'",
        ]
      
  spring-api:
    build:
      context: ../
    container_name: spring-api
    ports:
      - "8080:8080"
    links:
      - mongo
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - backend

volumes:
   mongo-data:

networks:
  backend: